name: Print Statement with Secret

on:
  push:
    branches:
      - main

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
    - name: Print Secret
      run: echo "My secret is ${{ secrets.MY_SECRET }}"
